line-smt-apis/force-app/main/default/objects/ActivityCarView__c.object
<CustomObject>
    <fields>
        <fullName>ActivityCarViewDate__c</fullName>
        <label>預約賞車日期</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ActivityID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Activity ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CarStyle__c</fullName>
        <label>車型</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>經銷商</label>
        <referenceTo>Dealer__c</referenceTo>
        <relationshipLabel>預約賞車</relationshipLabel>
        <relationshipName>ActivityCarViewToDealer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LineActivityCarViewID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Line 預約賞車 ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PowerType__c</fullName>
        <label>動力</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesRepresentative__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>銷售業代</label>
        <referenceTo>SalesRepresentative__c</referenceTo>
        <relationshipLabel>預約賞車</relationshipLabel>
        <relationshipName>ActivityCarViewToSalesRep</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Satisfaction__c</fullName>
        <label>滿意度</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>預約狀態</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>待確認</fullName>
                </value>
                <value>
                    <fullName>已確認</fullName>
                </value>
                <value>
                    <fullName>已取消</fullName>
                </value>
                <value>
                    <fullName>已完成</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>預約賞車</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>預約賞車編號</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

line-smt-apis/force-app/main/default/objects/Dealer__c.object
<CustomObject>
    <label>經銷商</label>
    <nameField>
        <label>經銷商名稱</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

line-smt-apis/force-app/main/default/objects/SalesRepresentative__c.object
<CustomObject>
    <fields>
        <fullName>Dealer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>經銷商名稱</label>
        <referenceTo>Dealer__c</referenceTo>
        <relationshipLabel>業代</relationshipLabel>
        <relationshipName>salesRepToDealer</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>業代</label>
    <nameField>
        <label>銷售業代</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/wrappers/ActivityCarViewWrapper.cls
global with sharing class ActivityCarViewWrapper extends DtoBase {
    public String lineActivityCarViewID {get; set;}
	public String activityID {get; set;}
	public String SMTLeadID {get; set;}
	public String salesRepresentativeCode {get; set;}
	public String dealerCode {get; set;}
	public String carStyle {get; set;}
	public String powerType {get; set;}
	public String status {get; set;}
	public String activityCarViewDate {get; set;}
    public String satisfaction {get; set;}
    
    global override String getSObjectName() {
        return 'ActivityCarView__c';
    }

    global override Map<String, Object> getSObjectMap() {
        return new Map<String, Object> {
            'LineActivityCarViewID__c' => this.lineActivityCarViewID,
            'ActivityID__c' => this.activityID,
            'SalesRepresentative__c' => this.salesRepresentativeCode,
            'Dealer__c' => this.dealerCode,
            'CarStyle__c' => this.carStyle,
            'PowerType__c' => this.powerType,
            'Status__c' => this.status,
            'ActivityCarViewDate__c' => this.activityCarViewDate,
            'Satisfaction__c' => this.satisfaction
        };
    }

    global static ActivityCarViewWrapper parseJson(String jsonString) {
        return (ActivityCarViewWrapper) System.JSON.deserialize(jsonString, ActivityCarViewWrapper.class);
    }
}