line-smt-apis/force-app/main/default/objects/ActivityCarView__c.object
<CustomObject>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>潛客</label>
        <referenceTo>Lead__c</referenceTo>
        <relationshipLabel>預約賞車</relationshipLabel>
        <relationshipName>ActivityCarViewToLead</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>LineActivityCarViewID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Line 預約賞車 ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>會員姓名</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>預約賞車</relationshipLabel>
        <relationshipName>ActivityCarViewToMember</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SalesRepresentative__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>銷售業代</label>
        <referenceTo>SalesRepresentative__c</referenceTo>
        <relationshipLabel>預約賞車</relationshipLabel>
        <relationshipName>ActivityCarViewToSalesRep</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>預約賞車</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>預約賞車編號</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

line-smt-apis/force-app/main/default/objects/Lead__c.object
<CustomObject>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>會員</label>
        <referenceTo>Member__c</referenceTo>
        <relationshipLabel>潛客</relationshipLabel>
        <relationshipName>LeadToMember</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SMTLeadId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>SMT潛客ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>SalesRepresentative__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>業代</label>
        <referenceTo>SalesRepresentative__c</referenceTo>
        <relationshipLabel>潛客</relationshipLabel>
        <relationshipName>LeadToSalesRep</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>潛客</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>潛客編號</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

line-smt-apis/force-app/main/default/objects/Member__c.object
<CustomObject>
    <label>會員</label>
    <nameField>
        <label>會員姓名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

line-smt-apis/force-app/main/default/objects/SalesRepresentative__c.object
<CustomObject>
    <fields>
        <fullName>SalesRepresentativeCode__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>銷售業代代碼</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>業代</label>
    <nameField>
        <label>銷售業代</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/apis/SmtActivityCarViewApi.cls
@RestResource(urlMapping = '/smt/activityCarView')
global class SmtActivityCarViewApi {

    @HttpPost
    global static void saveActivityCarViewAndSendLine() {
        RestRequest request = RestContext.request;
        RestResponse response = Restcontext.response;

        SmtActivityCarViewWrapper requestBodyWrapper = SmtActivityCarViewWrapper.parseJson(request.requestBody.toString());
        ActivityCarView__c requestBodyObject = (ActivityCarView__c) requestBodyWrapper.ToSObject();

        List<ActivityCarView__c> existingObjectList = [SELECT id, Member__c FROM ActivityCarView__c WHERE LineActivityCarViewID__c =: requestBodyWrapper.lineActivityCarViewID];
        if (existingObjectList == null || existingObjectList.isEmpty()) {
            response = ApiResponseUtil.buildErrorResponse(response, Constants.RESPONSE_ERROR_NOT_EXISTING);
            return;
        }

        List<Lead__c> existingLeadList = [SELECT Id FROM Lead__c WHERE SMTLeadId__c =: requestBodyWrapper.SMTLeadID];
        List<SalesRepresentative__c> existingSalesRepresentativeList = [SELECT Id FROM SalesRepresentative__c WHERE SalesRepresentativeCode__c =: requestBodyWrapper.salesRepresentativeCode];
        if (existingSalesRepresentativeList == null || existingSalesRepresentativeList.isEmpty()) {
            response = ApiResponseUtil.buildErrorResponse(response, Constants.RESPONSE_ERROR_NOT_EXISTING);
            return;
        }

        Lead__c newOrExistingLead = null;
        if (existingLeadList != null && existingLeadList.size() > 0) {
            newOrExistingLead = existingLeadList.get(0);
            requestBodyObject.Lead__c = newOrExistingLead.Id;
        } else {
            newOrExistingLead = new Lead__c();
            newOrExistingLead.SMTLeadId__c = requestBodyWrapper.SMTLeadID;
            newOrExistingLead.Member__c = existingObjectList.get(0).Member__c;
        }
        newOrExistingLead.SalesRepresentative__c = existingSalesRepresentativeList.get(0).Id;
        Database.upsert(newOrExistingLead);
        requestBodyObject.Lead__c = newOrExistingLead.Id;
        
        ActivityCarView__c existingObject = existingObjectList.get(0);
        requestBodyObject.Id = existingObject.Id;
        requestBodyObject = (ActivityCarView__c) SObjectUtil.updateFirstObjectWithNonNullValueOfSecondObject(existingObject, requestBodyObject);
        
        Database.UpsertResult dbResult = Database.upsert(requestBodyObject);
        if (dbResult.isSuccess()) {
            String jsonBodyAsString = JSON.serialize(new SmtToLineCarViewWrapper(requestBodyWrapper));
            LineCallout.lineFutureCallout(Constants.LINE_ENDPOINT_CAR_TEST, jsonBodyAsString);
        }
        ApiResponseUtil.buildRestResponseDependingDatabaseResponse(response, dbResult);
   }
    
}