line-smt-apis/force-app/main/default/objects/ActivityCarTest__c.object
<CustomObject>
    <fields>
        <fullName>ActivityCarTestDate__c</fullName>
        <label>預約試駕日期</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ActivityID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Activity ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>CarStyle__c</fullName>
        <label>車型</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CarTestRoute__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>試駕路線</label>
        <referenceTo>CarTestRoute__c</referenceTo>
        <relationshipLabel>預約試駕</relationshipLabel>
        <relationshipName>ActivityCarTestToCarTestRoute</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ChooseMethod__c</fullName>
        <label>選擇業代方式</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>自行指定</fullName>
                </value>
                <value>
                    <fullName>系統分配</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Companion__c</fullName>
        <label>同行伴侶</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>自己1人</fullName>
                </value>
                <value>
                    <fullName>和家人</fullName>
                </value>
                <value>
                    <fullName>和朋友</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Dealer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>經銷商名稱</label>
        <referenceTo>Dealer__c</referenceTo>
        <relationshipLabel>預約試駕</relationshipLabel>
        <relationshipName>ActivityCarTestToDealer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>GarageTestRequirement__c</fullName>
        <label>試車庫需求</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>需要</fullName>
                </value>
                <value>
                    <fullName>不需要</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LastTestCarStyle__c</fullName>
        <label>最後試乘車型</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LineActivityCarTestID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Line 預約試駕 ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PowerType__c</fullName>
        <label>動力</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PurchaseDecision__c</fullName>
        <label>是否購車</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>買車了好興奮</fullName>
                </value>
                <value>
                    <fullName>尚未決定購車</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SafetySeatQuantity__c</fullName>
        <label>安全座椅張數</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>SafetySeatRequirement__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1張</fullName>
                </value>
                <value>
                    <fullName>2張</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SafetySeatRequirement__c</fullName>
        <label>安全座椅需求</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>需要</fullName>
                </value>
                <value>
                    <fullName>不需要</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SalesRepresentative__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>銷售業代</label>
        <referenceTo>SalesRepresentative__c</referenceTo>
        <relationshipLabel>預約試駕</relationshipLabel>
        <relationshipName>ActivityCarTestToSalesRep</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Satisfaction__c</fullName>
        <label>滿意度</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>預約狀態</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>待確認</fullName>
                </value>
                <value>
                    <fullName>已確認</fullName>
                </value>
                <value>
                    <fullName>已取消</fullName>
                </value>
                <value>
                    <fullName>已完成</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>預約試駕</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>預約試駕編號</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ActivityCarTest__c/fields/ChooseSalesRepresentative__c.field-meta.xml
<CustomField>
    <fullName>ChooseSalesRepresentative__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>選擇銷售業代</label>
    <referenceTo>SalesRepresentative__c</referenceTo>
    <relationshipLabel>預約試駕</relationshipLabel>
    <relationshipName>ActivityCarTestToSalesRep</relationshipName>
    <type>Lookup</type>
</CustomField>

line-smt-apis/force-app/main/default/objects/CarTestRoute__c.object
<CustomObject>
    <fields>
        <fullName>Dealer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>經銷商</label>
        <referenceTo>Dealer__c</referenceTo>
        <relationshipLabel>試駕路線</relationshipLabel>
        <relationshipName>CarTestRouteToDealer</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>試駕路線</label>
    <nameField>
        <displayFormat>R-{00000000}</displayFormat>
        <label>試駕路線編號</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

line-smt-apis/force-app/main/default/objects/Dealer__c.object
<CustomObject>
    <label>經銷商</label>
    <nameField>
        <label>經銷商名稱</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

line-smt-apis/force-app/main/default/objects/SalesRepresentative__c.object
<CustomObject>
    <fields>
        <fullName>Dealer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>經銷商名稱</label>
        <referenceTo>Dealer__c</referenceTo>
        <relationshipLabel>業代</relationshipLabel>
        <relationshipName>salesRepToDealer</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>業代</label>
    <nameField>
        <label>銷售業代</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/wrappers/ActivityCarTestWrapper.cls
global with sharing class ActivityCarTestWrapper extends DtoBase {
    public String lineActivityCarTestID {get; set;}
    public String activityID {get; set;}
    public String SMTLeadID {get; set;}
    public String salesRepresentativeCode {get; set;}
    public String dealerCode {get; set;}
    public String carStyle {get; set;}
    public String powerType {get; set;}
    public String status {get; set;}
    public String activityCarTestDate {get; set;}
    public String companion {get; set;}
    public String safetySeatRequirement {get; set;}
    public String safetySeatQuantity {get; set;}
    public String garageTestRequirement {get; set;}
    public String carTestRouteCode {get; set;}
    public String purchaseDecision {get; set;}
    public String lastTestCarStyle {get; set;}
    public String satisfaction {get; set;}

    public String lineUID {get; set;}
    public String chooseMethod {get; set;}
    public String chooseSalesRepresentativeCode {get ;set;}
    
    global override String getSObjectName() {
        return 'ActivityCarTest__c';
    }

    global override Map<String, Object> getSObjectMap() {
        return new Map<String, Object> {
            'LineActivityCarTestID__c' => this.lineActivityCarTestID,
            'ActivityID__c' => this.activityID,
            'SalesRepresentative__c' => this.salesRepresentativeCode,
            'Dealer__c' => this.dealerCode,
            'CarStyle__c' => this.carStyle,
            'PowerType__c' => this.powerType,
            'Status__c' => this.status,
            'ActivityCarTestDate__c' => this.activityCarTestDate,
            'Companion__c' => this.companion,
            'SafetySeatRequirement__c' => this.safetySeatRequirement,
            'SafetySeatQuantity__c' => this.safetySeatQuantity,
            'GarageTestRequirement__c' => this.garageTestRequirement,
            'CarTestRoute__c' => this.carTestRouteCode,
            'PurchaseDecision__c' => this.purchaseDecision,
            'LastTestCarStyle__c' => this.lastTestCarStyle,
            'Satisfaction__c' => this.satisfaction,
            'ChooseMethod__c' => this.chooseMethod,
            'ChooseSalesRepresentative__c' => this.chooseSalesRepresentativeCode
        };
    }

    global static ActivityCarTestWrapper parseJson(String jsonString) {
        return (ActivityCarTestWrapper) System.JSON.deserialize(jsonString, ActivityCarTestWrapper.class);
    }
}