line-smt-apis/force-app/main/default/objects/ActivityCarTest__c.object
<CustomObject>
    <fields>
        <fullName>Companion__c</fullName>
        <label>同行伴侶</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>自己1人</fullName>
                </value>
                <value>
                    <fullName>和家人</fullName>
                </value>
                <value>
                    <fullName>和朋友</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>GarageTestRequirement__c</fullName>
        <label>試車庫需求</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>需要</fullName>
                </value>
                <value>
                    <fullName>不需要</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LineActivityCarTestID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Line 預約試駕 ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PurchaseDecision__c</fullName>
        <label>是否購車</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>買車了好興奮</fullName>
                </value>
                <value>
                    <fullName>尚未決定購車</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SafetySeatQuantity__c</fullName>
        <label>安全座椅張數</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>SafetySeatRequirement__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1張</fullName>
                </value>
                <value>
                    <fullName>2張</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Satisfaction__c</fullName>
        <label>滿意度</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>預約狀態</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>待確認</fullName>
                </value>
                <value>
                    <fullName>已確認</fullName>
                </value>
                <value>
                    <fullName>已取消</fullName>
                </value>
                <value>
                    <fullName>已完成</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>預約試駕</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>預約試駕編號</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/wrappers/LineActivityCarTestUpdateWrapper.cls
global class LineActivityCarTestUpdateWrapper extends DtoBase {
    public String lineActivityCarTestID {get; set;}
    public String status {get; set;}
    public String companion {get; set;}
    public String safetySeatQuantity {get; set;}
    public String garageTestRequirement {get; set;}
    public String carTestRouteID {get; set;}
    public String purchaseDecision {get; set;}
    public Integer satisfaction {get; set;}

    global override String getSObjectName() {
        return 'ActivityCarTest__c';
    }

    global override Map<String, Object> getSObjectMap() {
        return new Map<String, Object> {
            'LineActivityCarTestID__c' => this.lineActivityCarTestID,
            'Status__c' => this.status,
            'Companion__c' => this.companion,
            'SafetySeatQuantity__c' => this.safetySeatQuantity,
            'GarageTestRequirement__c' => this.garageTestRequirement,
            'PurchaseDecision__c' => this.purchaseDecision,
            'Satisfaction__c' => this.satisfaction
        };
    }

    global static LineActivityCarTestUpdateWrapper parseJson(String jsonString) {
        return (LineActivityCarTestUpdateWrapper) System.JSON.deserialize(jsonString, LineActivityCarTestUpdateWrapper.class);
    }
}