line-smt-apis/force-app/main/default/objects/ActivityCarTest__c.object
<CustomObject>
    <fields>
        <fullName>ActivityCarTestDate__c</fullName>
        <label>預約試駕日期</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>ActivityID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Activity ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>LineActivityCarTestID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Line 預約試駕 ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>PowerType__c</fullName>
        <label>動力</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>預約狀態</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>待確認</fullName>
                </value>
                <value>
                    <fullName>已確認</fullName>
                </value>
                <value>
                    <fullName>已取消</fullName>
                </value>
                <value>
                    <fullName>已完成</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>預約試駕</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>預約試駕編號</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ActivityCarTest__c/fields/CarModel__c.field-meta.xml
<CustomField>
    <fullName>CarModel__c</fullName>
    <label>車款</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/wrappers/SmtActivityCarTestWrapper.cls
global class SmtActivityCarTestWrapper extends DtoBase {
    public String lineActivityCarTestID {get; set;}
    public String activityID {get; set;}
    public String SMTLeadID {get; set;}
    public String salesRepresentativeCode {get; set;}
    public String carModel {get; set;}
    public String powerType {get; set;}
    public String status {get; set;}
    public String activityCarTestDate {get; set;}
    
    global override String getSObjectName() {
        return 'ActivityCarTest__c';
    }

    global override Map<String, Object> getSObjectMap() {
        return new Map<String, Object> {
            'LineActivityCarTestID__c' => this.lineActivityCarTestID,
            'ActivityID__c' => this.activityID,
            'CarModel__c' => this.carModel,
            'PowerType__c' => this.powerType,
            'Status__c' => this.status,
            'ActivityCarTestDate__c' => this.activityCarTestDate != null? Datetime.valueOf(this.activityCarTestDate) : null
        };
    }

    global static SmtActivityCarTestWrapper parseJson(String jsonString) {
        return (SmtActivityCarTestWrapper) System.JSON.deserialize(jsonString, SmtActivityCarTestWrapper.class);
    }
}