line-smt-apis/force-app/main/default/objects/ActivityCarView__c.object
<CustomObject>
    <fields>
        <fullName>LineActivityCarViewID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Line 預約賞車 ID</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Satisfaction__c</fullName>
        <label>滿意度</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>預約狀態</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>待確認</fullName>
                </value>
                <value>
                    <fullName>已確認</fullName>
                </value>
                <value>
                    <fullName>已取消</fullName>
                </value>
                <value>
                    <fullName>已完成</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>預約賞車</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>預約賞車編號</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/wrappers/LineActivityCarViewUpdateWrapper.cls
global with sharing class LineActivityCarViewUpdateWrapper extends DtoBase {
    public String lineActivityCarViewID {get; set;}
	public String status {get; set;}
	public String satisfaction {get; set;}
   
    global override String getSObjectName() {
        return 'ActivityCarView__c';
    }

    global override Map<String, Object> getSObjectMap() {
        return new Map<String, Object> {
            'LineActivityCarViewID__c' => this.lineActivityCarViewID,
            'Status__c' => this.status,
            'Satisfaction__c' => this.satisfaction
        };
    }

    global static LineActivityCarViewUpdateWrapper parseJson(String jsonString) {
        return (LineActivityCarViewUpdateWrapper) System.JSON.deserialize(jsonString, LineActivityCarViewUpdateWrapper.class);
    }
}