line-smt-apis/force-app/main/default/objects/CarTestRoute__c.object
<CustomObject>
    <fields>
        <fullName>CarTestRouteType__c</fullName>
        <label>試駕路線類型</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>市區道路</fullName>
                </value>
                <value>
                    <fullName>山區道路</fullName>
                </value>
                <value>
                    <fullName>高速道路</fullName>
                </value>
                <value>
                    <fullName>其他</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DrivingDistance__c</fullName>
        <label>距離</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DrivingTime__c</fullName>
        <label>車程</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GoogleMapLink__c</fullName>
        <label>GoogleMap連結</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>RouteDescription__c</fullName>
        <label>路線說明</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>TestDriveExperienceProject__c</fullName>
        <label>試駕體驗項目</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <label>試駕路線</label>
    <nameField>
        <displayFormat>R-{00000000}</displayFormat>
        <label>試駕路線編號</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/tests/default/classes/dataLoader/CarTestRouterDataLoader.cls
public with sharing class CarTestRouterDataLoader {
    
    public static void loadData() {
        CarTestRoute__c data = new CarTestRoute__c();

        data.GoogleMapLink__c = 'https://maps.google.com/';
        data.CarTestRouteType__c = Constants.PicklistCarTestRouteTypeUrban;
        data.TestDriveExperienceProject__c = 'OK';
        data.DrivingDistance__c = '100';
        data.RouteDescription__c = 'Dangerous';
        data.DrivingTime__c = 'Short';

        insert data;
    }
}