line-smt-apis/force-app/main/default/objects/CarTestRoute__c.object
<CustomObject>
    <fields>
        <fullName>Dealer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>經銷商</label>
        <referenceTo>Dealer__c</referenceTo>
        <relationshipLabel>試駕路線</relationshipLabel>
        <relationshipName>CarTestRouteToDealer</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>試駕路線</label>
    <nameField>
        <displayFormat>R-{00000000}</displayFormat>
        <label>試駕路線編號</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

line-smt-apis/force-app/main/default/objects/Dealer__c.object
<CustomObject>
    <fields>
        <fullName>DealerCode__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>經銷商代碼</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>經銷商</label>
    <nameField>
        <label>經銷商名稱</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/triggerhandlers/CarTestRouteTriggerHandler.cls
public with sharing class CarTestRouteTriggerHandler extends TriggerHandler {
    public CarTestRouteTriggerHandler() {
    }

    protected override void afterUpdate() {
        List<Id> dealerIdList = new List<Id>();
        for (CarTestRoute__c triggeredObject : (List<CarTestRoute__c>) Trigger.new) {
            dealerIdList.add(triggeredObject.Dealer__c);
        }
        List<Dealer__c> dealerList = [SELECT Id, DealerCode__c FROM Dealer__c WHERE Id in :dealerIdList];
        if (dealerList.isEmpty()) {
            return;
        }

        for (CarTestRoute__c triggeredObject : (List<CarTestRoute__c>) Trigger.new) {
            String objectAsJson = JSON.serialize(new CarTestRouteWrapper(triggeredObject, dealerList.get(0)));
            LineCallout.lineFutureCallout(Constants.LINE_ENDPOINT_CAR_TEST_ROUTE, objectAsJson);
        }
    }

    protected override void afterInsert() {
        List<Id> dealerIdList = new List<Id>();
        for (CarTestRoute__c triggeredObject : (List<CarTestRoute__c>) Trigger.new) {
            dealerIdList.add(triggeredObject.Dealer__c);
        }
        List<Dealer__c> dealerList = [SELECT Id, DealerCode__c FROM Dealer__c WHERE Id in :dealerIdList];
        if (dealerList.isEmpty()) {
            return;
        }

        for (CarTestRoute__c triggeredObject : (List<CarTestRoute__c>) Trigger.new) {
            String objectAsJson = JSON.serialize(new CarTestRouteWrapper(triggeredObject, dealerList.get(0)));
            LineCallout.lineFutureCallout(Constants.LINE_ENDPOINT_CAR_TEST_ROUTE, objectAsJson);
        }
    }
}