line-smt-apis/force-app/main/default/objects/CarTestRoute__c.object
<CustomObject>
    <fields>
        <fullName>CarTestRouteType__c</fullName>
        <label>試駕路線類型</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>市區道路</fullName>
                </value>
                <value>
                    <fullName>山區道路</fullName>
                </value>
                <value>
                    <fullName>高速道路</fullName>
                </value>
                <value>
                    <fullName>其他</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Dealer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>經銷商</label>
        <referenceTo>Dealer__c</referenceTo>
        <relationshipLabel>試駕路線</relationshipLabel>
        <relationshipName>CarTestRouteToDealer</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DrivingDistance__c</fullName>
        <label>距離</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DrivingTime__c</fullName>
        <label>車程</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>GoogleMapLink__c</fullName>
        <label>GoogleMap連結</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>RouteDescription__c</fullName>
        <label>路線說明</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <label>試駕路線</label>
    <nameField>
        <displayFormat>R-{00000000}</displayFormat>
        <label>試駕路線編號</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CarTestRoute__c/fields/CarTestExperienceProject__c.field-meta.xml
<CustomField>
    <fullName>CarTestExperienceProject__c</fullName>
    <label>試駕體驗項目</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

line-smt-apis/force-app/main/default/objects/Dealer__c.object
<CustomObject>
    <fields>
        <fullName>DealerCode__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>經銷商代碼</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>經銷商</label>
    <nameField>
        <label>經銷商名稱</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/wrappers/CarTestRouteWrapper.cls
public class CarTestRouteWrapper {
    public String CarTestRouteID {get; set;}
    public String DealerCode {get; set;}
    public String CarTestRouteType {get; set;}
    public String DrivingTime{get; set;}
    public String DrivingDistance {get; set;}
    public String RouteDescription {get; set;}
    public String GoogleMapLink {get; set;}
    public String CarTestExperienceProject {get; set;}
    
    public CarTestRouteWrapper(CarTestRoute__c givenSObject, Dealer__c dealerObject) {
        this.CarTestRouteID = givenSObject.Name;
        this.DealerCode = dealerObject.DealerCode__c;
        this.CarTestRouteType = givenSObject.CarTestRouteType__c;
        this.DrivingTime = givenSObject.DrivingTime__c;
        this.DrivingDistance = givenSObject.DrivingDistance__c;
        this.RouteDescription = givenSObject.RouteDescription__c;
        this.GoogleMapLink = givenSObject.GoogleMapLink__c;
        this.CarTestExperienceProject = givenSObject.CarTestExperienceProject__c;    
    }

}