line-smt-apis/force-app/main/default/objects/Dealer__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>地址</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Area__c</fullName>
        <label>區域</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>北</fullName>
                </value>
                <value>
                    <fullName>中</fullName>
                </value>
                <value>
                    <fullName>南</fullName>
                </value>
                <value>
                    <fullName>東</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>縣市</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Area__c</controllingField>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>台北市</fullName>
                </value>
                <value>
                    <fullName>新北市</fullName>
                </value>
                <value>
                    <fullName>基隆市</fullName>
                </value>
                <value>
                    <fullName>宜蘭縣</fullName>
                </value>
                <value>
                    <fullName>桃園市</fullName>
                </value>
                <value>
                    <fullName>新竹縣</fullName>
                </value>
                <value>
                    <fullName>新竹市</fullName>
                </value>
                <value>
                    <fullName>苗栗縣</fullName>
                </value>
                <value>
                    <fullName>台中市</fullName>
                </value>
                <value>
                    <fullName>彰化縣</fullName>
                </value>
                <value>
                    <fullName>南投縣</fullName>
                </value>
                <value>
                    <fullName>雲林縣</fullName>
                </value>
                <value>
                    <fullName>嘉義縣</fullName>
                </value>
                <value>
                    <fullName>嘉義市</fullName>
                </value>
                <value>
                    <fullName>台南市</fullName>
                </value>
                <value>
                    <fullName>高雄市</fullName>
                </value>
                <value>
                    <fullName>屏東縣</fullName>
                </value>
                <value>
                    <fullName>花蓮縣</fullName>
                </value>
                <value>
                    <fullName>台東縣</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DealerCode__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>經銷商代碼</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>DealerSystemCode__c</fullName>
        <label>經銷體系代碼</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DealerSystemName__c</fullName>
        <label>經銷體系名稱</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PhotoURL__c</fullName>
        <label>圖片URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>ServiceHours__c</fullName>
        <label>服務時間</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Telephone__c</fullName>
        <label>電話</label>
        <type>Phone</type>
    </fields>
    <label>經銷商</label>
    <nameField>
        <label>經銷商名稱</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dealer__c/fields/MapURL__c.field-meta.xml
<CustomField>
    <fullName>MapURL__c</fullName>
    <label>Google Map連結</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/wrappers/DealerWrapper.cls
public class DealerWrapper {
    public String DealerSystemCode {get; set;}
    public String DealerSystemName {get; set;}
    public String DealerCode {get; set;}
    public String Name {get; set;}
    public String Area {get; set;}
    public String City {get; set;}
    public String Address {get; set;}
    public String Telephone {get; set;}
    public String ServiceHours {get; set;}
    public String PictureURL {get; set;}
    public String GPSLng {get; set;}
    public String GPSLat {get; set;}
    public String MapURL {get; set;}

    public DealerWrapper(Dealer__c givenSObject) {
        this.DealerSystemCode = givenSObject.DealerSystemCode__c;
        this.DealerSystemName = givenSObject.DealerSystemName__c;
        this.DealerCode = givenSObject.DealerCode__c;
        this.Name = givenSObject.Name;
        this.Area = givenSObject.Area__c;
        this.City = givenSObject.City__c;
        this.Address = givenSObject.Address__c;
        this.Telephone = givenSObject.Telephone__c;
        this.ServiceHours = givenSObject.ServiceHours__c;
        this.PictureURL = givenSObject.PhotoURL__c;
        this.GPSLng = String.valueOf(givenSObject.GPSlLngLat__longitude__s);
        this.GPSLat = String.valueOf(givenSObject.GPSlLngLat__latitude__s);
        this.MapURL = givenSObject.MapURL__c;
    }
}