line-smt-apis/force-app/main/default/objects/Lead__c.object
<CustomObject>
    <fields>
        <fullName>LeadLevel__c</fullName>
        <label>潛客級別</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>A級</fullName>
                </value>
                <value>
                    <fullName>B級</fullName>
                </value>
                <value>
                    <fullName>C級</fullName>
                </value>
                <value>
                    <fullName>H級</fullName>
                </value>
                <value>
                    <fullName>失聯</fullName>
                </value>
                <value>
                    <fullName>退訂</fullName>
                </value>
                <value>
                    <fullName>無效</fullName>
                </value>
                <value>
                    <fullName>戰敗</fullName>
                </value>
                <value>
                    <fullName>簽訂</fullName>
                </value>
                <value>
                    <fullName>其他</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SMTLeadId__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>SMT潛客ID</label>
        <length>20</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>SalesRepresentative__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>業代</label>
        <referenceTo>SalesRepresentative__c</referenceTo>
        <relationshipLabel>潛客</relationshipLabel>
        <relationshipName>LeadToSalesRep</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>潛客</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>潛客編號</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/ExSalesRepresentative__c.field-meta.xml
<CustomField>
    <fullName>ExSalesRepresentative__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>前銷售業代</label>
    <referenceTo>SalesRepresentative__c</referenceTo>
    <relationshipLabel>潛客 (前銷售業代)</relationshipLabel>
    <relationshipName>ExSalesRepresentative</relationshipName>
    <type>Lookup</type>
</CustomField>

line-smt-apis/force-app/main/default/objects/SalesRepresentative__c.object
<CustomObject>
    <label>業代</label>
    <nameField>
        <label>銷售業代</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/wrappers/LeadWrapper.cls
global with sharing class LeadWrapper extends DtoBase {
    public String SMTLeadID {get; set;}
    public String salesRepresentativeCode {get; set;}
    public String exSalesRepresentativeCode {get; set;}
    public String leadLevel {get; set;}

    global override String getSObjectName() {
        return 'Lead__c';
    }

    global override Map<String, Object> getSObjectMap() {
        return new Map<String, Object> {
            'SMTLeadId__c' => this.SMTLeadID,
            'SalesRepresentative__c	' => this.salesRepresentativeCode,
            'ExSalesRepresentative__c' => this.exSalesRepresentativeCode,
            'LeadLevel__c' => this.leadLevel
        };
    }

    global static LeadWrapper parseJson(String jsonString) {
        return (LeadWrapper) System.JSON.deserialize(jsonString, LeadWrapper.class);
    }
}