line-smt-apis/force-app/main/default/objects/Member__c.object
<CustomObject>
    <fields>
        <fullName>Birthday__c</fullName>
        <label>生日</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>CellPhone__c</fullName>
        <label>手機</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>性別</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>先生</fullName>
                </value>
                <value>
                    <fullName>小姐</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>LineUID__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>LINE_UID</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>會員</label>
    <nameField>
        <label>會員姓名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/wrappers/MemberWrapper.cls
global with sharing class MemberWrapper extends DtoBase {
    public String lineUID {get; set;}
    public String name {get; set;}
    public String gender {get; set;}
    public String cellPhone {get; set;}
    public String email {get; set;}
    public String birthday {get; set;}

    global override String getSObjectName() {
        return 'Member__c';
    }

    global override Map<String, Object> getSObjectMap() {
        return new Map<String, Object> {
            'LineUID__c' => this.lineUID,
            'Name' => this.name,
            'Gender__c' => this.gender,
            'CellPhone__c' => this.cellPhone,
            'Email__c' => this.email,
            'Birthday__c' => this.birthday
        };
    }

    global static MemberWrapper parseJson(String jsonString) {
        return (MemberWrapper) System.JSON.deserialize(jsonString, MemberWrapper.class);
    }
}