line-smt-apis/force-app/main/default/objects/Promotion__c.object
<CustomObject>
    <fields>
        <fullName>CarModel__c</fullName>
        <label>車款</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CarStyle__c</fullName>
        <label>車型</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PromotionContent__c</fullName>
        <label>優惠內容</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>PromotionMonth__c</fullName>
        <label>優惠月份</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PromotionYear__c</fullName>
        <label>優惠年份</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>狀態</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>啟用</fullName>
                </value>
                <value>
                    <fullName>停用</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SuggestedPrice__c</fullName>
        <label>建議售價</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>YearType__c</fullName>
        <label>年式</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>當月優惠</label>
    <nameField>
        <displayFormat>P-{00000000}</displayFormat>
        <label>優惠編號</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Promotion__c/fields/CarName__c.field-meta.xml
<CustomField>
    <fullName>CarName__c</fullName>
    <label>車名</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Promotion__c/fields/CarSeries__c.field-meta.xml
<CustomField>
    <fullName>CarSeries__c</fullName>
    <label>車系</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/wrappers/PromotionWrapper.cls
global with sharing class PromotionWrapper {
    public String PromotionID {get; set;}
    public String PromotionYear {get; set;}
    public String PromotionMonth {get; set;}
    public String CarSeries {get; set;}
    public String CarModel {get; set;}
    public String CarStyle {get; set;}
    public String CarName {get; set;}
    public String YearType {get; set;}
    public String SuggestedPrice {get; set;}
    public String PromotionContent {get; set;}
    public String Status {get; set;}

    public PromotionWrapper(Promotion__c promotionObject) {
        
        this.PromotionID = promotionObject.Id;
        this.PromotionYear = promotionObject.PromotionYear__c;
        this.PromotionMonth = promotionObject.PromotionMonth__c;
        
        this.CarSeries = promotionObject.CarSeries__c;
        this.CarModel = promotionObject.CarModel__c;
        this.CarStyle = promotionObject.CarStyle__c;
        this.CarName = promotionObject.CarName__c;

        this.YearType = promotionObject.YearType__c;
        this.SuggestedPrice = promotionObject.SuggestedPrice__c;
        this.PromotionContent = promotionObject.PromotionContent__c;
        
        this.Status = promotionObject.Status__c;

    }

}