line-smt-apis/force-app/main/default/objects/SalesRepresentative__c.object
<CustomObject>
    <fields>
        <fullName>SalesRepresentativeCode__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>銷售業代代碼</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>業代</label>
    <nameField>
        <label>銷售業代</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/apis/SmtSalesRepresentativeApi.cls
@RestResource(urlMapping = '/smt/salesrepresentative')
global with sharing class SmtSalesRepresentativeApi {
    
    @HttpPost
    global static void saveSalesRepresentativeAndSendLine() {
        RestRequest request = RestContext.request;
        RestResponse response = Restcontext.response;

        SalesRepresentativeWrapper requestBodyWrapper = SalesRepresentativeWrapper.parseJson(request.requestBody.toString());
        SalesRepresentative__c requestBodyObject = (SalesRepresentative__c) requestBodyWrapper.ToSObject();

        SalesRepresentative__c existingObject = [SELECT Id FROM SalesRepresentative__c WHERE SalesRepresentativeCode__c =: requestBodyWrapper.salesRepresentativeCode];
        if (existingObject != null) {
            requestBodyObject.Id = existingObject.Id;
            requestBodyObject = (SalesRepresentative__c) SObjectUtil.updateFirstObjectWithNonNullValueOfSecondObject(requestBodyObject, existingObject);
        }

        Database.UpsertResult dbResult = Database.upsert(requestBodyObject);
        ApiResponseUtil.buildRestResponseDependingDatabaseResponse(response, dbResult);
   }
}