line-smt-apis/force-app/main/default/objects/SalesRepresentative__c.object
<CustomObject>
    <fields>
        <fullName>CellPhone__c</fullName>
        <label>手機</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>LineID__c</fullName>
        <label>LINE_ID</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LineLink__c</fullName>
        <label>LINE連結</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>NickName__c</fullName>
        <label>暱稱</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>QRCodeLink__c</fullName>
        <label>QRcode連結</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>SalesRepresentativeCode__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>銷售業代代碼</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>SelfRecommendedContent__c</fullName>
        <label>自我推薦內容</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Telephone__c</fullName>
        <label>電話</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>WorkingStatus__c</fullName>
        <label>在職狀態</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>在職</fullName>
                </value>
                <value>
                    <fullName>離職</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>業代</label>
    <nameField>
        <label>銷售業代</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/wrappers/SalesRepresentativeWrapper.cls
global with sharing class SalesRepresentativeWrapper extends DtoBase {
    public String salesRepresentativeCode {get; set;}
    public String salesRepresentativeName {get; set;}
    public String dealerCode {get; set;}
    public String nickname {get; set;}
    public String cellPhone {get; set;}
    public String telephone {get; set;}
    public String lineID {get; set;}
    public String lineLink {get; set;}
    public String selfRecommendedContent {get; set;}
    public String workingStatus {get; set;}
    public String QRCodeLink {get; set;}
    public String Email {get; set;}

    global override String getSObjectName() {
		  return 'SalesRepresentative__c';
	  }

	global override Map<String, Object> getSObjectMap() {
		return new Map<String, Object> {
			'SalesRepresentativeCode__c' => this.salesRepresentativeCode,
			'Name' => this.salesRepresentativeName,
			'NickName__c' => this.nickname,
			'CellPhone__c' => this.cellPhone,
			'Telephone__c' => this.telephone,
      'LineID__c' => this.lineID,
      'LineLink__c' => this.lineLink,
      'SelfRecommendedContent__c' => this.selfRecommendedContent,
      'WorkingStatus__c' => this.workingStatus,
      'QRCodeLink__c' => this.QRCodeLink
		};
  }
  
  global static SalesRepresentativeWrapper parseJson(String jsonString) {
    return (SalesRepresentativeWrapper) System.JSON.deserialize(jsonString, SalesRepresentativeWrapper.class);
  }
}